### PR TITLE
memory optimizations from neonsecret and Doggettx

### PR DESCRIPTION
**Pull request by 007**
Includes optimizations from [Doggettx](https://github.com/Doggettx/stable-diffusion) and [neonsecret](https://github.com/neonsecret/stable-diffusion) forks to reduce memory requirements pretty massively.

### CODE REVIEW

**Comment by 007** [comment]
@neonsecret @doggettx tks for excellent memory fixes!

**Comment by neonsecret** [comment]
yeah np, but you should've merged from my fork so we are listed as contributors or something


anyways at list credit us somewhere

**Comment by Doggettx** [comment]
> @neonsecret @Doggettx tks for excellent memory fixes!

Hey np, I've done some fixes since then though, most important one is that the free memory wasn't always correct which is fixed in the latest version.

https://github.com/Doggettx/stable-diffusion

**Comment by neonsecret** [comment]
> > @neonsecret @Doggettx tks for excellent memory fixes!
> 
> Hey np, I've done some fixes since then though, most important one is that the free memory wasn't always correct which is fixed in the latest version.
> 
> https://github.com/Doggettx/stable-diffusion

actually it isn't correct now either, I'm working on fixing it

**Pull request merged**
